name: JOIN US
description: Application for joining translation team
labels: [Join Us]
title: "Join Application"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for applying to join us!
        Before joining, there are some brief questions.
        **⚠️ Please do not change the title!**
        Note: Due to time zones, it takes about 0-24 hours to process your application, but you can create a branch, make changes in your own branch first, and then publish them by open a pull request.
  - type: checkboxes
    id: Experience
    attributes:
      label: Experience
      options:
        - label: I known how to use GitHub
        - label: I known how the mod works
        - label: I known python and LLM.
  - type: input
    attributes:
      label: Your languages
      placeholder:
  - type: textarea
    id: others
    attributes:
      label: Any More?