name: Others
description: Ask a question rather than a bug report.
labels: ["question"]
body:
  - type: textarea
    id: describe
    attributes:
      label: The problems you have encountered?
    validations:
      required: false
