on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Get latest release version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "Latest Version: $VERSION"

          # Ensure VERSION matches the release asset naming convention
          if [[ ! "$VERSION" =~ ^v ]]; then
            VERSION="v$VERSION"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download release asset
        run: |
          echo "Using Version: $VERSION"

          wget "https://github.com/${{ github.repository }}/releases/download/${VERSION}/${VERSION#v}.zip" -O ${VERSION}.zip

          ls -la ${VERSION}.zip

          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: nickelc/upload-to-modio@v2.1.0
        with:
          token: ${{ secrets.MODIO_TOKEN }}
          game: 3659
          mod: 5238039
          version: ${{ env.VERSION }}
          path: ${{ env.VERSION }}.zip